# Generated by Django 4.0.5 on 2022-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('under construction', 'under construction'), ('in store', 'in store'), ('in the way', 'in the way'), ('delivered', 'delivered')], default='under construction', max_length=50, null=True),
        ),
    ]
