# Generated by Django 4.0.5 on 2022-07-15 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
